# Generated by Django 5.0.6 on 2024-06-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('content', models.CharField(default='Description', max_length=10000)),
                ('publication_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
