# Generated by Django 5.0.6 on 2024-06-26 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['title'], 'verbose_name_plural': 'Articles'},
        ),
    ]
